voxpupuli/puppet-jira

README.md
jira.yaml
manifests/init.pp
spec/classes/jira_config_spec.rb
templates/server.xml.erb

This PR will add template code to be able to add a context path for the JIRA Tomcat instance. 
I need this in companion with my reverse proxy, as I have a context path in my apache in which I add the reverse proxy configuration.
I added some validations in init.pp, too. (For $contextpath, $proxy and $db).

Add <Context> path attribute as a parameter for jira class

---

manifests/init.pp

Adds Oracle to the list of databases that can pass validation, and correct connection string for Oracle databases.

Add oracle to validate and correct jdbc syntax

---

README.md
manifests/init.pp
manifests/service.pp
spec/classes/jira_service_spec.rb

Use case is when something like JDK is updated underneath jira, you'd want the service to restart, with:
```puppet
subscribe => Package['jdk']
```
I tested separately, services work fine with something like:
```puppet 
notify => undef
```
in the service definition.

Add a notify and subscribe options to the jira service

---

spec/classes/jira_config_spec.rb

Added tests for Microsoft SQL Server, per Issue #54.
I based it off the existing tests but was unable to run the test suite via rake due a protocol error unrelated to what I added (tried it without my modification).  This was the first time I've written or run spec tests so I think it is related to my setup, not necessarily the tests.
Also my apologies, I wasn't sure how to connect this to the existing issue.

Add MS SQL Server tests

---

manifests/facts.pp
spec/classes/jira_facts_spec.rb
templates/facts.rb.erb

I had trouble updating my recent installation of jira as the fact could not be executed (error 404 without the context).
This adds the proper contextpath to the url.
Includes a proper rspec test in classes/jira_facts_spec.rb.

Adding contextpath support to facter jira custom fact.

---

README.md
manifests/facts.pp
manifests/init.pp
spec/classes/jira_config_spec.rb
templates/server.xml.erb

Add a new parameter, jira::tomcatAddress, which is passed through to the Tomcat's Connector configuration. Useful for environments where Jira is deployed behind a reverse proxy such as Nginx.
The parameter defaults to undef, and if left unset, the Connector configuration will not include the address= parameter (i.e. existing installations will be unchanged)
A new rspec test has been provided to test this functionality.

Provide capability to set Tomcat's bind address

---

spec/classes/jira_config_spec.rb
templates/server.xml.erb

It had been generating an invalid `address` config of the `<Connector>`. Adding a spec test for it.
Fixes my comment in #67 .

Fix server.xml template

---

manifests/init.pp
spec/classes/jira_config_spec.rb
spec/classes/jira_init_spec.rb
templates/server.xml.erb

Fixes #55.
* This includes validation and error messages for the AJP settings hash.
* Adds spec testing for the template and for the validation.

Adding rspec tests for AJP connector and fixing template code for AJP

---

README.md

I recently implemented a fully-automated Jira install using puppet/jira where the server was connecting to a remote Oracle DB and the parameters (especially jira::dburl) took some time to tune to successfully build a working configuration.  I figure this extra documentation might help someone in the same situation.

Added hieradata examples for Oracle DB backend.

---

manifests/params.pp

The Amazon AMI $::osfamily is /RedHat/, but the $::operatingsystem is /Amazon/ and the $::operatingsystemmajrelease is /2015/.  This causes it to enter the conditional logic, and pass though without any value for $json_packages, $service_file_location, $service_file_template, and $service_lockfile.
This initial commit is the smallest possible change to fix the error I noticed.  I simply added a conditional to look for the Amazon $::operatingsystem value where we are using the init provider under the RedHat $::osfamily
I added a basic failure message as the default value if no conditions are met under the RedHat $::osfamily case.
A more complete solution could be made similar to the params.pp in https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/params.pp.
I haven't …

No case for Amazon AMI

---

.travis.yml
manifests/install.pp
metadata.json

When using the mysql_connector download, the file is often times downloaded after the service is started.  This fix uses the contain function to make sure the mysql_connector class is contained in the install class, thus fixing dependancies.
It also updates the travis tests and the metadata.json to use the minimum versions of puppet that have the contain class.  This means that anyone still using Puppet Enterprise < 3.2 will not be able to use this module anymore, but that version has been long unsupported by Puppet Labs so this should not be an issue.

Fix mysql connector containment

---

README.md
metadata.json

Due to bug PUP-1597 (https://tickets.puppetlabs.com/browse/PUP-1597), this module will raise an
error during catalog compilation ("Error: undefined method `ref' for nil:NilClass") when run with a
version of Puppet prior to 3.7 if "mysql" is used as the database.
Here is the commit that triggers the bug:
https://github.com/puppet-community/puppet-jira/commit/412efe3e7accb892bceadcf59b2d32f063faeb06#diff-a276806bea2dfcf1f57c33aee19c7309R114

Update required Puppet version to 3.7

---

manifests/init.pp
spec/classes/jira_mysql_connector_spec.rb

It seems http://cdn.mysql.com only hosts the latest version of mysql-connector-java, which is
currently 5.1.38. However, jira::mysql_connector_versions specifies an old version (5.1.34), which
results in a 404:
http://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-5.1.34.tar.gz
Fortunately, it seems https://dev.mysql.com/ has all the old versions. Plus, it uses SSL.
https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.34.tar.gz

Fix jira::mysql_connector_url

---

manifests/init.pp
manifests/install.pp
spec/classes/jira_config_spec.rb
spec/classes/jira_install_deploy_spec.rb
spec/classes/jira_install_staging_spec.rb
templates/server.xml.erb

Updates `server.xml` with JIRA 7's default settings and continues to support the installation and management of JIRA pre-7.

Jira 7 Support

---

README.md
jira.yaml
manifests/init.pp
spec/classes/jira_install_deploy_spec.rb
spec/classes/jira_install_staging_spec.rb

The download URL appears to have moved as a lookup on the current URL
returns two HTTP 301 responses and one HTTP 302.
This patch replaced the current download URL with the redirected one and switches the protocol to use HTTPS.
```
$ curl -sIL http://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-6.4.12.tar.gz | egrep '(HTTP|Location)'
HTTP/1.1 301 Moved Permanently
Location: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-6.4.12.tar.gz
HTTP/1.1 301 Moved Permanently
Location: https://my.atlassian.com/software/jira/downloads/binary/atlassian-jira-6.4.12.tar.gz
HTTP/1.1 302 Found
Location: https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-6.4.12.tar.gz
HTTP/1.1 200 OK
```

Change Default Download URL and use HTTPS

---

README.md
manifests/config.pp
manifests/init.pp
spec/classes/jira_config_spec.rb
templates/cluster.properties.erb

Setting up a node for a JIRA datacenter requires this additional file to be created and specification of a shared location.

Adding template and configuration item for JIRA Datacenter

---

manifests/init.pp
templates/server.xml.erb

When JIRA is ran on a server with existing tomcat instance, the shutdown port conflicts (hardcoded to 8005). This PR adds a param to init.pp to override the default.

adding ability to change tomcatShutdownPort

---

manifests/params.pp
manifests/service.pp

Debian Jessie can use systemd units instead Init.d-scripts.
This is just a squash merge of https://github.com/voxpupuli/puppet-jira/pull/99

Systemd support for debian 8 jessie

---

manifests/params.pp
spec/classes/jira_service_spec.rb

Fix to https://github.com/voxpupuli/puppet-jira/issues/122. Check that the Debian-variant is not Ubuntu before opting to use systemd rather than initd.

Ubuntu initd

---

README.md
files/seraph-config_withSSO.xml
manifests/init.pp
manifests/sso.pp
spec/classes/jira_sso_spec.rb
templates/crowd.properties

Add crowd's single sign on feature to jira. When using delegated authentication via Atlassian Crowd, you are able to activate this feature according to Atlassian's documentation at https://confluence.atlassian.com/display/CROWD/Integrating+Crowd+with+Atlassian+JIRA#IntegratingCrowdwithAtlassianJIRA-2.2ConfigureJIRAtouseCrowd%27sAuthenticatortoenableSSO%28Optional%29

Add crowd single sign-on functionality

---

README.md
manifests/init.pp
templates/server.xml.erb

When using a proxy or port redirection, I don't want Jira to add the port 8443 to the url. So I need Jira to redirect to port 443 even if the tomcat https port is 8443 and then I manage the 443 myself to redirect to 8443. Simple change and defaults is the same as before.
In my case: $tomcat_native_ssl = true and $tomcat_redirect_https_port       =  443
We can discuss how to require native_ssl if redirect_https_port is set?

New custom https redirect port

---

templates/jira.initscript.erb

Turns out that the check for the status of the jira server was always returning a state of 'stopped'
This was due to the jps task always having an exit status of 1 even thou the jira service was running.
have chaged this to simply look for a process owened by the jira user

Service status is not working when using init scripts

---

manifests/install.pp

Atlassian has changed name convention for JIRA Software 7.2+. This commit fixes it.

Fixed JIRA 7.1.x download URL.

---

README.md
manifests/install.pp
spec/classes/jira_install_spec.rb

As well, tests specify jira 6.0.0, it's 6.0
Fix jira 6.0 source/download urls
fix jira 6 version as well...
Changing 6.0 to 6.1 as less then 6.1 is EOL
match jira 6.1 source and download urls
While fixing tests for Jira 6.0, I noticed that versions < 6.1 are end of support by Atlassian:
[End Of Support](https://confluence.atlassian.com/jira064/supported-platforms-720411857.html)
I changed the test to use 6.1 instead.

Atlassian doesn't provide checksums, add checksum_verify false.

---

manifests/init.pp
manifests/install.pp

This PR addresses the concerns of my previous (incorrect) hardcoding of checksum_verify (as the default for that is 'true' in archive module) in install.pp and exposes it with a conditional in init.pp instead. It sets the value depending on whether checksum is defined by user and performs the check, otherwise it does no check. 
@dhoppe @afisher @bbriggs @bastelfreak (and anyone else), please review. Thanks!

Exposes checksum_verify in init.pp w/ conditional.

---

README.md
files/check-java.sh
manifests/config.pp
manifests/init.pp
spec/classes/jira_config_spec.rb
templates/check-java.sh.erb

The script which checks for Java assumes Oracle Java, and thus wrongly
checks the version string output to be prefixed with 'java' and not
'openjdk'. This change removes the check for JIRA 7 and up.
Signed-off-by: Trevor Bramwell <tbramwell@linuxfoundation.org>

Allow management of vendor check-java.sh file

---

spec/acceptance/default_parameters_spec.rb

Fairly sure I had amended this before but at any rate that didn't make it into the last PR #197. Most likely (PEBCAK) 😈 
This fixes:
- The version check doesn't match version

FIX version checking regex 

---

manifests/init.pp
templates/server.xml.erb

Tomcat connector protocol changed in Jira 7.3:
https://confluence.atlassian.com/jiracore/jira-core-7-3-x-upgrade-notes-861251104.html
This will allow you to set the correct connector value (org.apache.coyote.http11.Http11NioProtocol) when using Jira 7.3 and higher.

Add $tomcat_protocol_ssl paramater for compatibility with Jira >= 7.3.

---

manifests/init.pp
templates/server.xml.erb

Improvement on #219, will now default to the correct ssl connector protocol value for any jira version.

Set tomcat_protocol_ssl based on jira version if undef

---

manifests/init.pp

storage_engine is deprecated in favor of default_storage_engine. As of JIRA 7.3.x using the storage_engine results in a startup error.

Correct jdbc storage engine parameter.

---

manifests/facts.pp
manifests/params.pp

If sharing the same server for several atlassian products (crowd, jira, confluence, bitbucket) there may be conflicts with packages.  This shows up with the bitbucket and jira modules both expecting one or both of `rubygem-json` and `ruby-json`.  Switching to `ensure_packages` allows both projects to declare the package requirement.
Correspond PR in related project: https://github.com/danofthewired/puppet-bitbucket/pull/60

switch to using ensure_packages to avoid conflicts

---

README.md
jira.yaml
manifests/config.pp
manifests/init.pp
spec/classes/jira_config_spec.rb
templates/dbconfig.h2.xml.erb
templates/dbconfig.oracle.xml.erb
templates/dbconfig.postgresql.xml.erb
templates/dbconfig.sqlserver.xml.erb

Add Support for H2 database and add sensible defaults for other db related params.
Fixes #254 
Fixes #73

Add Support for H2 Database and Fix #73 

---

templates/server.xml.erb

If you set `$product = 'servicedesk'` (which allows you to install the Jira Service Desk application, a superset of Jira Server), its versioning is currently in the 3.x range, which hits this line in `server.xml.erb` and causes the older JasperListener to be called at startup and it will fail.  This has been tested with `$product = 'servicedesk'` and `$version = '3.12.2'`.

Update server.xml.erb to account for weird Service Desk versioning

---

templates/context.xml.erb
templates/server.xml.erb

Seems that per https://confluence.atlassian.com/jirakb/jira-throws-java-io-filenotfoundexception-warnings-after-upgrade-869007981.html the scanner was always off by default, so it should be safe to just set it to false.
Fixes #234

Remove messy warnings. Fixes #234

---

manifests/init.pp
spec/classes/jira_init_spec.rb

replace validate_* with assert_type in init.pp

---

templates/server.xml.erb

Notes:
https://confluence.atlassian.com/jirasoftware/jira-software-7-13-x-upgrade-notes-957135908.html
Add relaxedPath attributes into tomcat config to support Jira 7.13+

Added relaxedPath xml attributes as per jira apache tomcat upgrade file

---

jira.yaml
manifests/init.pp
spec/classes/jira_install_spec.rb

Fixes #285
Also replace `Variant[Stdlib::HTTPUrl, Stdlib::HTTPSUrl]` with just
`Stdlib::HTTPUrl` as that already allows `https` URLs.

Update default `download_url`

---

manifests/params.pp

"if versioncmp($facts['operatingsystemmajrelease'], '7') >= 0" is erroneously true for Amazon Linux 2018 in our observation. I reworked the logic to better test for Amazon Linux vs RHEL/CentOS 6/7.
No issue exists for this change.

Better Amazon support

---

templates/server.xml.erb

Pull request of #260 (issue #259) wanted to prevent JasperListener to be
activated for Service Desk. Version comp condition can't be fulfilled as
Jira and Service Desk have different version numbers.
Therefore JasperListener gets added to the server.xml anyway with Service Desk. To get Service Desk working we need to adapt the condition to not match when we run Jira Service Desk.
Also relaxedPath options only needed from Jira version >v7.12.1 and Service Desk
(According to https://confluence.atlassian.com/jirakb/changing-server-xml-to-handle-requests-with-special-characters-958453799.html)
We need to have relaxedPathChars and relaxedQueryChars set according to
the FAQ page of Atlassian with Jira version greater than 7.12.1 and
apparently Service Desk.
Issue does not exist (yet), relates …

Jira Service Desk doesn't start with JasperListener / need relaxedPath with correct version comp

---

manifests/init.pp

While upgrading JIRA we currently using the recommended path as defined by Atlassian support. Due to issues between versions our final upgrade path was the following. 
```
6.3.10 > 6.3.15 > 6.4.14 > 7.0.0 > 7.0.11 > 7.6.10
```
While installing `7.0.0` the download path was defined incorrectly as the following. 
```
https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-7.0.0-jira-7.0.0.tar.gz
```
While it should be the following (with the software name)
```
https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-7.0.0-jira-7.0.0.tar.gz
```
* Added `=` to the case statement that allows for versions `7.0.0` and above, including version `7.0.0` in `init.pp` file.

Added >= to capture version 7.0.0 as using the "software" url

---

manifests/facts.pp
spec/classes/jira_facts_spec.rb

Updates `jira::facts` to check for the OSS version of the Puppet AIO agent. If the OSS Puppet AIO agent is installed it will set `facts.rb` to use the version of ruby that comes with the AIO agent.
Fixes #151

Update jira::facts to check for Puppet AIO agent

---

README.md
manifests/init.pp
spec/classes/jira_config_spec.rb
spec/type_aliases/tomcat_attributes_spec.rb
spec/type_aliases/tomcat_connectors_spec.rb
templates/server.xml.erb
types/tomcat_attributes.pp
types/tomcat_connectors.pp

Add a new, optional class parameter `jira::tomcat_additional_connectors`
whose value is a well-formed, complex hash as described by the new type
aliases `Jira::Tomcat_connectors` and `Jira::Tomcat_attributes`. Each
hash key represents a port number, and the key's value is a hash that
describes the connector's attributes and their values.
Useful for defining additional HTTP ports through which to access Jira.
A typical use case is when Jira and Confluence run behind a reverse
proxy and application links between Jira and Confluence must be set up.
Then it is often better to allow Jira and Confluence to communicate
directly instead of through the reverse proxy, but this requires a
Tomcat connector that is configured for direct access instead of reverse
proxy access (`proxyName`, `proxyPort`, …

Allow defining additional Tomcat connectors

---

README.md

this yaml code for jira::java_opts with incorrect apostrophe generates with the template `JAVA_OPTS="<%= scope.lookupvar('jira::java_opts') %> $JAVA_OPTS"` incorrect code 
```
JAVA_OPTS="-Datlassian.mail.senddisabled=true -Datlassian.mail.fetchdisabled=true -Datlassian.mail.popdisabled=true'
$JAVA_OPTS"
```
which generates then error
```
/opt/jira/atlassian-jira-software-8.13.0-standalone/bin/catalina.sh: eval: line 517: unexpected EOF while looking for matching `''
/opt/jira/atlassian-jira-software-8.13.0-standalone/bin/catalina.sh: eval: line 519: syntax error: unexpected end of file
```
In fact, without apostrophe, it still generates linebreak in `JAVA_OPTS`, and then jira does not start. I will create ticket for this issue.

remove incorrect apostrophe in example

---

manifests/init.pp
manifests/mysql_connector.pp
spec/classes/jira_mysql_connector_spec.rb
templates/setenv.sh.erb

The change is needed to specificy and use a mysql-connector version > 8. The problem with those connectors is, that there is no "-bin" suffix in the jarfile and therefore the suffix needs to be empty. As the current String will require the string to be at least 1 character long, a version 8 connector can not be configured.
```
class {'jira':
...
mysql_connector_manage       => true,
mysql_connector_version      => '8.0.23',
mysql_connector_install      => '/opt/MySQL-connector',
mysql_connector_url          => 'https://dev.mysql.com/get/Downloads/Connector-J',
mysql_connector_jar_suffix   => '', # no '-bin'!
...
```
results in 
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Jira]: …

Fixing that the suffix can be empty as well (needed for mysql-connector > 8)

---

manifests/facts.pp
spec/classes/jira_facts_spec.rb

There is nothing sensitive about the content of this script, so let's use the standard mode 0755 used for executables.

facts.pp: use less restrictive mode for the external fact script

---

templates/facts.rb.erb

templates/facts.rb.erb: update URI.open syntax to fix deprecation warnings
Fixes #330.

templates/facts.rb.erb: update URI.open syntax to fix deprecation warnings

---

spec/acceptance/default_parameters_spec.rb

Version 9.4 doesn't exist in the postgresql.org repos anymore, which caused this test to fail. Simply using the default version that the puppetlabs-postgresql module wants works fine.

acceptance tests: use the default version of postgresql

---

manifests/params.pp

Fixes: 23242f9f7a68f6d0728bc2c3d7b1198570f69b34
Now I do notice that my patch ends up moving the .service file on Debian-based OSes from /lib/systemd to /usr/lib/systemd. It was marked as a backwards incompatible change but it may still surprise users. Thoughts?

Fix unit tests after sysvinit patch broke them

---

manifests/facts.pp
spec/classes/jira_facts_spec.rb

On Puppet Enterprise the aio_agent_version fact should also be set so it's redundant.
The json_packages code is made generic so it's executed on all non-AIO installs.

Remove special code path for Puppet Enterprise

---

spec/classes/jira_facts_spec.rb

In 6364236b8a9296f527647fd5738254772f6c1e00 a wrong path was checked and somehow the tests didn't run so was merged. This corrects the expectation.
Fixes: 6364236b8a9296f527647fd5738254772f6c1e00

Fix Ruby path expectation

---

manifests/facts.pp
spec/classes/jira_facts_spec.rb
templates/facts.rb.erb

Use localhost instead of 127.0.0.1 so that we don't discriminate against IPv6-only configurations.

facts.pp: use localhost instead of 127.0.0.1

---

README.md
templates/check-java.sh.erb
templates/server.xml.erb

Updates check-java.sh and server.xml templates to upstream version. Especially the check-java update is required, when using a java version > 8 (or 1.8, depending which versioning scheme you look at.
Fixes #339 
Kind of fixes #300 
This replaces PR #317.

Updating check-java.sh and server.xml templates to upstream version

---

README.md
manifests/init.pp
spec/classes/jira_config_spec.rb
templates/server.xml.erb

Adding handling for X-Forwarded-For in access logs
If a proxy operates before JIRA, the access logs will only contain the IPs of the proxy instead of the IP of the user. With X-Forwarded-For the proxy can forward the users IP to the JIRA application server so that it can be logged correctly

Add handling for X-Forwarded-For in access logs

---

manifests/init.pp
spec/classes/jira_config_spec.rb
templates/setenv.sh.erb

The _additional API is not useful at all; if people want to fully override their configuration, they can set their JDK type to custom
Test fixes missing for now, but I've tested this against an actual Jira instance

Restore $jira::java_opts for compatibility and remove $jira::jvm_*_additional from the API, as setting JDK type to custom allows full control anyway.

---

manifests/init.pp
spec/classes/jira_config_spec.rb
templates/dbconfig.xml.epp

Needs the dbconfig refactoring PR first. Adds an API to control JDBC connection parameters.

Allow specifying JDBC connection parameters with jira::connection_settings

---

jira.yaml
manifests/config.pp
manifests/init.pp
manifests/install.pp
spec/acceptance/default_parameters_spec.rb
spec/acceptance/mysql_spec.rb
spec/classes/jira_config_spec.rb
spec/classes/jira_install_spec.rb
spec/classes/jira_mysql_connector_spec.rb
spec/classes/jira_sso_spec.rb
spec/classes/jira_upgrade_spec.rb
spec/default_module_facts.yml
templates/server.xml.epp

Anything pre jira 8.0.0 is already EOL.
Drop support; legacy users can still use the old version of the module and use it to upgrade.
This only fixes manifests, I'll do templates separately. EDIT: ended up fixing templates anyway...

Drop support for JIRA <8.0.0

---

README.md
manifests/config.pp
manifests/init.pp
spec/classes/jira_config_spec.rb
spec/type_aliases/jvm_types_spec.rb
templates/setenv.sh.epp
types/jvm_types.pp

This undeprecates $java_opts for backwards compatibility
and repurposes the other parameters to do what a custom $jvm_type
did previously.
It removes "-XX:HeapDumpOnOutOfMemoryError" because that's
not a default setting in the upstream setenv.sh
It also makes setting $jvm_permgen a no-op, since JIRA doesn't support
JDK older than 8 anymore and the option does nothing

Sync setenv.sh with upstream 8.13.5 (LTS)

---

README.md
manifests/init.pp
manifests/install.pp
spec/acceptance/default_parameters_spec.rb
spec/acceptance/mysql_spec.rb
spec/classes/jira_config_spec.rb

This simplifies most configurations

Provide option to install a java package directly via this module

---

manifests/install.pp

`$installdir` can be owned by root
Fixes #255

$installdir was previously unnecessarily owned by the jira user. It will now be owned by root.

---

README.md
manifests/config.pp
manifests/init.pp
spec/classes/jira_config_spec.rb

Add support for Oracle service names
Adds $oracle_use_sid, that if set to false modified the JDBC
URL syntax to connect to an Oracle database via a service name.
Also, tests.
Fixes #283

Add support for Oracle service names

---

.github/workflows/ci.yml
metadata.json

Let's see what the tests say about this. Fixes #361

Add newer OSes and Puppet 7 to test matrix, drop Puppet 5

---

manifests/config.pp
spec/classes/jira_config_spec.rb
templates/dbconfig.xml.epp

Turns out JIRA works without these, but will complain, at least on
some versions. Also make the approach to variable naming a bit more
consistent.

Configure dbconfig.xml parameters explicitly to stop JIRA's healthcheck from complaining

---

README.md

Doc fixes only, so CI should be mostly irrelevant

Add note about RHEL 8 and SELinux and clean up a bit

---

manifests/config.pp
manifests/init.pp
spec/acceptance/mysql_spec.rb
spec/classes/jira_config_spec.rb
templates/dbconfig.xml.epp

For PostgreSQL only. Also fixes #380

Configure recommended JDBC connection-properties by default for PostgreSQL databases

---

manifests/init.pp

The current version check does not take the JIRA servicedesk package into account. This package has an other versioning schema - see here: https://www.atlassian.com/de/software/jira/service-management/download-archives
Currently, if the following parameters are choosen to init the jira class, the output shows
`JIRA versions older than 8.0.0 are no longer supported. Please use an older version of this module to upgrade first`
```puppet
class { 'jira':
#
version   => '4.17.0',
product  => 'servicedesk',
...
```

Extend the version check to the tailored jira servicedesk version

---

spec/classes/jira_config_spec.rb
templates/server.xml.epp

Using the `proxy` parameter when `tomcat_native_ssl` is true results in a string literal of "key" in server.xml in the SSL connector.
Pull request address that by using the previously declared `$key` variable in the EPP template.
n/a

use variable instead of literal in server.xml

---

.editorconfig
.github/CONTRIBUTING.md
.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
.msync.yml
.overcommit.yml
.pmtignore
.rspec
.rspec_parallel
.rubocop.yml
.sync.yml
.yardopts
Dockerfile
Gemfile
Rakefile
spec/spec_helper.rb

modulesync 4.2.0

---

.github/workflows/ci.yml
.sync.yml
manifests/config.pp
manifests/init.pp
spec/acceptance/default_parameters_spec.rb
spec/acceptance/mysql_spec.rb
spec/classes/jira_config_spec.rb
spec/classes/jira_install_spec.rb
spec/classes/jira_mysql_connector_spec.rb
spec/classes/jira_sso_spec.rb
spec/spec_helper.rb
spec/support/acceptance/constants.rb
spec/type_aliases/jvm_types_spec.rb
templates/dbconfig.jndi.xml.epp
templates/dbconfig.xml.epp
templates/server.xml.epp

Added feature to install custom plugins and use JNDI database connections
n/a

Allow custom plugin installation and usage of JNDI database connections

---

spec/classes/jira_config_spec.rb
templates/server.xml.epp

- Added negation logic when `scheme` key is present when iterating through the proxy hash.
- Added additional test for `tomcat_native_ssl` without proxy settings.
Fixes #395

Avoid duplicate scheme declaration when using proxy with SSL

---

templates/setenv.sh.epp

The version variable in puppet-jira can be either set to the jira software version or the servicedesk version. manifests/init.pp correctly differentiates but this template if statement does not, so the if statement does not apply to servicedesk > 4.11, missing out on an essential JVM parameter.
This PR adds in some and/ors to differentiate.
n/a

Update setenv.sh.epp if statement to work with service desk

---

templates/setenv.sh.epp

See https://jira.atlassian.com/browse/JRASERVER-76224 for details on this. This snippet was taken directly from the setenv.sh script from JIRA 9.11.1.
This PR updates setenv.sh with the fix from atlassian's upstream setenv.sh script. It simply checks if java 17 is in use, and if so, then it includes the JVM_OPENS parameters.
Fixes #412

Bugfix java 17 support per atlassian upstream

---

REFERENCE.md
manifests/config.pp
manifests/init.pp
spec/acceptance/default_parameters_spec.rb
spec/acceptance/mysql_spec.rb
spec/classes/jira_config_spec.rb
templates/dbconfig.xml.epp

From JIRA 10.3 on the password in the dbconfig.xml gets replaced with {ATL_SECURED} after JIRA has read-in the password and encrypted it into it's local password store.
Add the change_dbpassword parameter. Unless it is set to true the password will not be written into dbconfig.xml

Add "change database password" parameter - JIRA >10.3

---

README.md
metadata.json
spec/acceptance/default_parameters_jira_10_spec.rb
spec/acceptance/mysql_spec.rb

- #452
- **Drop support for EOL Ubuntu 18.04 and Ubuntu 20.04**

Drop support for EOL Ubuntu 18.04 and Ubuntu 20.04

---

metadata.json

Commit 7dd0828d518c2664105495887622250fc9ca7910 (#445) introduced stdlib::deferrable_epp() which was introduced in stdlib 8.4.0 in https://github.com/puppetlabs/puppetlabs-stdlib/commit/c1127f26a024c6fd91ecd1de75122670aabb129d.

`metadata.json`: increase `puppetlabs/stdlib` minimum version to 8.4.0
