voxpupuli/puppet-jira

- README.md
- jira.yaml
- manifests/config.pp
- manifests/init.pp
- templates/dbconfig.sqlserver.xml.erb
I added support for Microsoft SQL Server.  I've tested against SQL Server 2012 and based on Atlassian's documentation it should work for 2005-2012.
It uses the JTDS driver bundled in the default/preferred installation method.
Please let me know if you have any questions.  
Thank you.
> Added Microsoft SQL Server support

- jira.yaml
- manifests/init.pp
- templates/server.xml.erb
I tried to make it similar to the way that proxy is set up, such that you can add additional parameters to the Connector object.
> Turn on the AJP connector based on a hiera or puppet-variable lookup

- .travis.yml
- Gemfile
raised issue https://github.com/rodjek/rspec-puppet/issues/254
> Force rspec-puppet 1.0.1, version 2 has issues

- spec/classes/jira_service_spec.rb
- spec/fixtures/manifests/site.pp
Following up from [here](https://github.com/brycejohnson/puppet-jira/pull/58#issuecomment-73761920), some extra specs. Turns out rspec-puppet is pretty awesome.
Thanks to @zachdaniel for help figuring out the extra package resource.
> Added in some extra specs as requested

- README.md
- manifests/init.pp
- manifests/install.pp
- spec/classes/jira_install_deploy_spec.rb
- spec/classes/jira_install_staging_spec.rb
Add param 'shell', defaults to '/bin/true'
Update tests
> Issue #51 Make the jira users shell configurable

- manifests/config.pp
- manifests/init.pp
- spec/classes/jira_config_spec.rb
- templates/context.xml.erb
Intended for use with JIRA plugin 'Database Custom Field'.
> Adding new feature generating a content.xml configuration. 

- .travis.yml
- CHANGELOG.md
- README.md
- metadata.json
- Update metadata, README, CHANGELOG to point to new namespace
- Update .travis.yml to auto deploy tagged versions
> Point to puppet-community name space.

- manifests/init.pp
- spec/classes/jira_config_spec.rb
- templates/setenv.sh.erb
in some cases its needed to comment in DISABLE_NOTIFICATIONS in setenv.sh. this pull request will add this function to this module.
> added new parameter disable_notifications in relation to setenv.sh

- Rakefile
Relates to this issue:
https://github.com/garethr/puppet-module-skeleton/issues/75
Relates to this PR:
https://github.com/garethr/puppet-module-skeleton/pull/76
> Make sure rake lint tasks work as expected

- README.md
- examples/jira_mysql_nativessl_install.pp
- manifests/init.pp
- spec/acceptance/mysql_spec.rb
- spec/classes/jira_config_spec.rb
- spec/spec_helper_acceptance.rb
- templates/server.xml.erb
> Add SSL Support #76

- README.md
- jira.yaml
- manifests/init.pp
- spec/classes/jira_config_spec.rb
- templates/dbconfig.postgresql.xml.erb
- templates/dbconfig.sqlserver.xml.erb
Paramaterize the schema value in the dbconfig.xml template.
> Dev azaugg parameterise schema

- README.md
- manifests/config.pp
- manifests/init.pp
- spec/classes/jira_config_spec.rb
- templates/jira-config.properties.erb
Adding configuration option to enable or disable websudo.
> Adding configuration option to enable or disable websudo.

- manifests/init.pp
- spec/classes/jira_init_spec.rb
> Check for required parameter javahome

- .sync.yml
- README.md
- Rakefile
- examples/jira_mysql_nativessl_install.pp
- jira.yaml
- manifests/config.pp
- manifests/facts.pp
- manifests/init.pp
- manifests/install.pp
- manifests/mysql_connector.pp
- spec/acceptance/default_parameters_spec.rb
- spec/acceptance/mysql_spec.rb
- spec/classes/jira_config_spec.rb
- spec/classes/jira_install_staging_spec.rb
- spec/classes/jira_mysql_connector_spec.rb
- templates/dbconfig.mysql.xml.erb
- templates/dbconfig.oracle.xml.erb
- templates/dbconfig.postgresql.xml.erb
- templates/dbconfig.sqlserver.xml.erb
- templates/server.xml.erb
Please merge. 
I am aware that these changes require a new major version, but there are to many for a smooth migration.
> Remove uppercase parameters

- .fixtures.yml
- README.md
- manifests/init.pp
- manifests/install.pp
- metadata.json
- spec/classes/jira_install_spec.rb
- spec/spec_helper_acceptance.rb
> Use module voxpupuli/archive instead of mkrakowitzer/deploy

- spec/classes/jira_config_spec.rb
- templates/server.xml.erb
I removed the conditional statement relating to JasperListener to fix Issue #135 
Hope that helps :)
> Issue #135 Fix

- .rubocop.yml
- Rakefile
- spec/acceptance/default_parameters_spec.rb
- spec/acceptance/mysql_spec.rb
- spec/classes/jira_config_spec.rb
- spec/classes/jira_facts_spec.rb
- spec/classes/jira_init_spec.rb
- spec/classes/jira_install_spec.rb
- spec/classes/jira_mysql_connector_spec.rb
- spec/classes/jira_service_spec.rb
- spec/classes/jira_sso_spec.rb
- spec/classes/jira_upgrade_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
> Update based on voxpupuli/modulesync_config

- .gitignore
- .msync.yml
- .rubocop.yml
- .travis.yml
- CHANGELOG.md
- Gemfile
- Rakefile
- manifests/facts.pp
- metadata.json
- spec/classes/jira_config_spec.rb
- spec/classes/jira_mysql_connector_spec.rb
- spec/classes/jira_service_spec.rb
- spec/fixtures/manifests/site.pp
> Modulesync 0.12.5 & Release 2.1.0

- manifests/install.pp
> Fix version 7.1.9 up

- manifests/init.pp
- spec/classes/jira_config_spec.rb
- templates/server.xml.erb
this one should be more clean and without my git mess :)
> adding access log format variable to init class

- .gitignore
- .msync.yml
- .rubocop.yml
- .sync.yml
- Gemfile
- spec/acceptance/nodesets/docker/centos-5.yml
- spec/acceptance/nodesets/docker/centos-6.yml
- spec/acceptance/nodesets/docker/centos-7.yml
- spec/acceptance/nodesets/docker/debian-7.yml
- spec/acceptance/nodesets/docker/debian-8.yml
- spec/acceptance/nodesets/docker/ubuntu-12.04.yml
- spec/acceptance/nodesets/docker/ubuntu-14.04.yml
- spec/acceptance/nodesets/docker/ubuntu-16.04.yml
- spec/classes/jira_config_spec.rb
- spec/default_module_facts.yml
- spec/spec_helper.rb
> modulesync 0.15.0

- README.md
- manifests/init.pp
- templates/dbconfig.mysql.xml.erb
> fixes issue #162 - add pool_test_on_borrow to dbconfig.mysql.xml.erb

- CHANGELOG.md
- metadata.json
Since we have made changes to init class as well as a number of fixes that block module usage, I'm proposing a major release with this PR.
> Major RELEASE PR

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .msync.yml
- .travis.yml
- spec/spec_helper.rb
Latest update from voxpupuli modulesync_config.
> Modulesync 0.16.1

- .msync.yml
- spec/spec_helper.rb
Latest update from voxpupuli modulesync_config.
> modulesync 0.16.2

- spec/acceptance/default_parameters_spec.rb
- spec/acceptance/mysql_spec.rb
Bump jira version in acceptance to '6.3.4a' (match to classes tests)
Bump jdk to 8 in these acceptance tests as well.
Replaces #187  (credit and thanks to @dhoppe for that work which this utilizes as well), provided @dhoppe is cool with that; the checksum blocker there I believe was addressed in #191.
> Fixup [default_parameters,mysql]_spec.rb acceptance tests

- README.md
Fixing the typo I introduced in #192.
> Fix 'script_check_java_manage' README description

- .msync.yml
- .sync.yml
- .travis.yml
- spec/spec_helper_acceptance.rb
This is towards enabling travis docker acceptance testing. Another modulesync PR for this module forthcoming (.sync.yml). That PR will have the docker/centos-7 and docker/debian-8 nodesets.
> Docker acceptance tests for travis

- spec/acceptance/default_parameters_spec.rb
- spec/acceptance/mysql_spec.rb
Remove duplicate lines in acceptance tests. Resolves #206 test errors.
> Fix #206 rubocop failures

- .msync.yml
- Rakefile
- examples/jira_mysql_install.pp
- examples/jira_postgres_install.pp
- examples/jira_postgres_nginx_install.pp
- examples/jira_postgres_nginx_ssl_install.pp
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/mysql_connector.pp
- spec/acceptance/nodesets/docker/centos-7.yml
- spec/acceptance/nodesets/docker/debian-8.yml
- spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml
- spec/acceptance/nodesets/ec2/image_templates.yaml
- spec/acceptance/nodesets/ec2/rhel-73-x64.yml
- spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml
- spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml
- spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml
- spec/classes/jira_config_spec.rb
- spec/classes/jira_facts_spec.rb
- spec/classes/jira_init_spec.rb
- spec/classes/jira_install_spec.rb
- spec/classes/jira_mysql_connector_spec.rb
- spec/classes/jira_service_spec.rb
- spec/classes/jira_sso_spec.rb
- spec/classes/jira_upgrade_spec.rb
> modulesync 0.20.1

- manifests/init.pp
- manifests/service.pp
- manifests/sso.pp
- metadata.json
- spec/classes/jira_service_spec.rb
- spec/classes/jira_sso_spec.rb
> replace validate_* with datatypes

- .github/CONTRIBUTING.md
- .msync.yml
- .overcommit.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- spec/classes/jira_config_spec.rb
- spec/classes/jira_facts_spec.rb
- spec/classes/jira_init_spec.rb
- spec/classes/jira_install_spec.rb
- spec/classes/jira_mysql_connector_spec.rb
- spec/classes/jira_service_spec.rb
- spec/classes/jira_sso_spec.rb
- spec/classes/jira_upgrade_spec.rb
- spec/spec_helper_acceptance.rb
> Modulesync 0.21.0

- .github/CONTRIBUTING.md
- .gitignore
- .msync.yml
- .rspec_parallel
- .rubocop.yml
- .sync.yml
- .travis.yml
- Gemfile
- Rakefile
- manifests/init.pp
- spec/acceptance/default_parameters_spec.rb
- spec/acceptance/mysql_spec.rb
- spec/acceptance/nodesets/archlinux-2-x64.yml
- spec/acceptance/nodesets/docker/ubuntu-14.04.yml
- spec/acceptance/nodesets/docker/ubuntu-16.04.yml
- spec/classes/jira_service_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
The modulesync had failed so many times; I just deleted the old branch / PR and created this one.
We already put in a fix for the templating thing that was causing the rubocop failure with 1.1.0.
> modulesync 1.2.0

- .sync.yml
- .travis.yml
> add acceptance tests on ubuntu 14.04

- manifests/init.pp
- manifests/install.pp
- spec/classes/jira_install_spec.rb
> Issue #215 - Disable user, need to update spec tests

- metadata.json
> bump archive dep to allow latest version

- README.md
- manifests/init.pp
- manifests/install.pp
> Add proxy support for 'archive'

- spec/spec_helper_acceptance.rb
> bump mysql dependency version to allow 5.x

- CHANGELOG.md
- metadata.json
> release 3.5.0

- templates/server.xml.erb
This change is to address https://github.com/voxpupuli/puppet-jira/issues/259
> Update server.xml.erb to allow for jsd

- CHANGELOG.md
- metadata.json
> release 3.5.1

- .msync.yml
- .sync.yml
- .travis.yml
- Gemfile
- metadata.json
- spec/spec_helper_acceptance.rb
> modulesync 1.9.6; update all dependencies

- .github/CONTRIBUTING.md
- .msync.yml
- .overcommit.yml
- .travis.yml
- Gemfile
- metadata.json
> modulesync 2.1.0 and allow puppet 6.x

- .fixtures.yml
- .msync.yml
- Gemfile
- spec/classes/coverage_spec.rb
- spec/default_facts.yml
- spec/spec_helper.rb
> modulesync 2.2.0

- manifests/init.pp
- metadata.json
- spec/classes/jira_config_spec.rb
- templates/cluster.properties.erb
Add additional options for configuring the "ehcache" settings in cluster.properties (https://developer.atlassian.com/server/jira/platform/configuring-a-jira-cluster/)
Fixes #245
> Add Ehcache options; require stdlib 4.25.0

- README.md
Updates documentation to reflect PR #286.
n/a
> Update `download_url` default value in documentation

- .github/CONTRIBUTING.md
- .msync.yml
- Gemfile
- manifests/sso.pp
- spec/spec_helper.rb
> modulesync 2.8.0

- .fixtures.yml
- README.md
- manifests/init.pp
- manifests/install.pp
- manifests/mysql_connector.pp
- metadata.json
- spec/classes/jira_mysql_connector_spec.rb
- spec/default_module_facts.yml
Remove support for the deprecated staging module
Fixes #313, #293, #103, #77
> Remove support for the deprecated staging module

- manifests/mysql_connector.pp
The mysql connector library might as well be world-readable.
> Make MySQL connector library world-readable

- README.md
Also fixes #150 by documenting that parent directories must exist
> Minor doc updates to make them more modern.

- metadata.json
- spec/spec_helper_acceptance.rb
also contains https://github.com/voxpupuli/puppet-jira/pull/362
> puppetlabs/stdlib: Allow 7.x

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .msync.yml
- Dockerfile
- Gemfile
- spec/classes/jira_config_spec.rb
- spec/classes/jira_mysql_connector_spec.rb
> modulesync 4.1.0

- metadata.json
> Test with Ubuntu 20.04

- .sync.yml
this is blocking https://github.com/voxpupuli/modulesync_config/pull/709
> fix broken .sync.yaml

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Release 5.1.0

- metadata.json
- spec/spec_helper_acceptance.rb
Blocked by:
* https://github.com/puppetlabs/puppetlabs-inifile/pull/460
* https://github.com/puppetlabs/puppetlabs-java/pull/493
* https://github.com/puppetlabs/puppetlabs-java/pull/497
> Allow up-to-date dependencies

- .github/CONTRIBUTING.md
- .github/labeler.yml
- .github/release.yml
- .github/workflows/ci.yml
- .github/workflows/labeler.yml
- .github/workflows/release.yml
- .msync.yml
- .overcommit.yml
- .puppet-lint.rc
- .rspec
- .sync.yml
- Gemfile
- spec/spec_helper.rb
> modulesync 9.1.0

- REFERENCE.md
- manifests/init.pp
- manifests/install.pp
This will add 'manage_homedir' parameter
Fixes #392
> Add `manage_homedir` parameter

- metadata.json
- **modulesync 9.2.0**
- **modulesync 9.3.0**
- **puppet/systemd: allow 8.x**
> Allow puppet/systemd 8.x
